apiVersion: v1
kind: Service
metadata:
  name: nutriscan-service
  namespace: nutriscan
  labels:
    app: nutriscan
spec:
  type: ClusterIP
  selector:
    app: nutriscan
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
